apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: frontend
    env: {{ .Values.app.env }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replica }}
  selector:
    matchLabels:
      app: frontend
      env: {{ .Values.app.env }}
  template:
      metadata:
        name: web-app
        labels:
          app: frontend
          env: {{ .Values.app.env }}
        namespace: {{ .Values.app.namespace }}
      spec:
        containers:
          - name: web-app-container
            image: gcr.io/spry-district-340607/webapp-color:{{ .Values.app.tag}}
            ports:
              - containerPort: 8080
            type: LoadBalancer