apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-color.fullname" . }}
  labels:
    app: frontend
    env: {{ .Values.app.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
    env: {{ .Values.app.env }}
